### PR TITLE
WIP: Comprehensive support to R2R transforms.

### LINKED ISSUE #8: Segmentation fault when R2R transform
Hello,

I just tried to adapt example/example.py into a 2R2 transform but I get a segmentation fault a the Plan object creation. It doesn't happen with other types of transforms. 
Digging a little bit, the fault seems to occur line 869 of core.pyx:
`cdef pfft_plan_func func = PFFT_PLAN_FUNC[self.type]`
 I remarked too there were no  Type.R2R : Type.R2R in the dictionary 'inverse' of the method 'inverse' of class Type but I don't know if those are related.

Have you experienced such behavior?

Best regards and thank you for this great wrapper!

Simon

### PR DESCRIPTION
**Pull request by rainwoodman**
This is a work in progress PR to add comprehensave support to R2R transforms.

- [X] Fixes #8.
- [ ] Add a basic correctness test on the H2RC and RC2H R2R transform
- [ ] Add the interface to specify different kinds / directions for R2C transform axes.
- [ ] Find the roundtrip transform pairs and add test cases to roundtrip.py.

### CODE REVIEW

**Comment by rainwoodman** [comment]
Use case example FFTW:

https://github.com/knaidoo29/falcon/blob/cb3555ac8b45090bb80d5624b09212cc2a353b79/reference/NumCal.cpp

It is not the R2HC transform.

**Comment by rainwoodman** [comment]
https://github.com/GEM3D/pressurePoissonSolver/blob/e9c5152d12885cf911e66fc6ec7f1dc3e9101264/domain_decomp/3D-petsc-example/PatchSolvers/FftwPatchSolver.cpp

**Comment by rainwoodman** [comment]
https://github.com/GEM3D/pressurePoissonSolver/blob/e9c5152d12885cf911e66fc6ec7f1dc3e9101264/domain_decomp/2D-example/Domain.cpp

**Comment by sbird** [comment]
Rebased so the test case runs

**Pull request merged**
